### ISSUE TITLE
Seems to be missing permissions for exact scheduling.

### ISSUE THREAD

**Issue by devcarbon-com** [v1tzor/TimePlanner#87]
Perhaps it is a new permission required by Android bramble.
```
type: crash
osVersion: google/bramble/bramble:14/UP1A.231105.001/2023111500:user/release-keys
package: ru.aleshin.timeplanner:27
process: ru.aleshin.timeplanner
processUptime: 35931 + 273 ms
installer: org.fdroid.basic

java.lang.SecurityException: Caller ru.aleshin.timeplanner needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:311)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1093)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1045)
	at android.app.AlarmManager.setExactAndAllowWhileIdle(AlarmManager.java:1321)
	at p5.c$a.a(SourceFile:93)
	at J5.d$a.g(SourceFile:14)
	at J5.d$a.h(SourceFile:200)
	at J5.d$a.d(SourceFile:1)
	at J5.d$a$c.q(SourceFile:13)
	at x2.a.j(SourceFile:12)
	at a4.W.run(SourceFile:99)
	at f4.m$a.run(SourceFile:4)
	at h4.k.run(SourceFile:3)
	at h4.a.A(SourceFile:1)
	at h4.a$c.d(SourceFile:15)
	at h4.a$c.p(SourceFile:29)
	at h4.a$c.run(SourceFile:1)
	Suppressed: f4.i: [CoroutineName(H5.d:K5.e:default:ScreenModelCoroutineScope), N0{Cancelling}@4d94ed0, Dispatchers.IO]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2981)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:181)
	at android.os.Binder.execTransactInternal(Binder.java:1368)
	at android.os.Binder.execTransact(Binder.java:1299)


```

**Comment by v1tzor** [comment]
It seems that I managed to solve this problem, check in the new version later
